// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: attachment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Attachment_PlainText
	//	*Attachment_ExecutedShellCommand
	//	*Attachment_RunningShellCommand
	//	*Attachment_DriveObject
	//	*Attachment_DiffHunk
	//	*Attachment_DiffSet
	//	*Attachment_DocumentContent
	Value         isAttachment_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_attachment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetValue() isAttachment_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attachment) GetPlainText() string {
	if x != nil {
		if x, ok := x.Value.(*Attachment_PlainText); ok {
			return x.PlainText
		}
	}
	return ""
}

func (x *Attachment) GetExecutedShellCommand() *ExecutedShellCommand {
	if x != nil {
		if x, ok := x.Value.(*Attachment_ExecutedShellCommand); ok {
			return x.ExecutedShellCommand
		}
	}
	return nil
}

func (x *Attachment) GetRunningShellCommand() *RunningShellCommand {
	if x != nil {
		if x, ok := x.Value.(*Attachment_RunningShellCommand); ok {
			return x.RunningShellCommand
		}
	}
	return nil
}

func (x *Attachment) GetDriveObject() *DriveObject {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DriveObject); ok {
			return x.DriveObject
		}
	}
	return nil
}

func (x *Attachment) GetDiffHunk() *DiffHunk {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DiffHunk); ok {
			return x.DiffHunk
		}
	}
	return nil
}

func (x *Attachment) GetDiffSet() *DiffSet {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DiffSet); ok {
			return x.DiffSet
		}
	}
	return nil
}

func (x *Attachment) GetDocumentContent() *DocumentContent {
	if x != nil {
		if x, ok := x.Value.(*Attachment_DocumentContent); ok {
			return x.DocumentContent
		}
	}
	return nil
}

type isAttachment_Value interface {
	isAttachment_Value()
}

type Attachment_PlainText struct {
	PlainText string `protobuf:"bytes,1,opt,name=plain_text,json=plainText,proto3,oneof"`
}

type Attachment_ExecutedShellCommand struct {
	ExecutedShellCommand *ExecutedShellCommand `protobuf:"bytes,2,opt,name=executed_shell_command,json=executedShellCommand,proto3,oneof"`
}

type Attachment_RunningShellCommand struct {
	RunningShellCommand *RunningShellCommand `protobuf:"bytes,3,opt,name=running_shell_command,json=runningShellCommand,proto3,oneof"`
}

type Attachment_DriveObject struct {
	DriveObject *DriveObject `protobuf:"bytes,4,opt,name=drive_object,json=driveObject,proto3,oneof"`
}

type Attachment_DiffHunk struct {
	DiffHunk *DiffHunk `protobuf:"bytes,5,opt,name=diff_hunk,json=diffHunk,proto3,oneof"`
}

type Attachment_DiffSet struct {
	DiffSet *DiffSet `protobuf:"bytes,6,opt,name=diff_set,json=diffSet,proto3,oneof"`
}

type Attachment_DocumentContent struct {
	DocumentContent *DocumentContent `protobuf:"bytes,7,opt,name=document_content,json=documentContent,proto3,oneof"`
}

func (*Attachment_PlainText) isAttachment_Value() {}

func (*Attachment_ExecutedShellCommand) isAttachment_Value() {}

func (*Attachment_RunningShellCommand) isAttachment_Value() {}

func (*Attachment_DriveObject) isAttachment_Value() {}

func (*Attachment_DiffHunk) isAttachment_Value() {}

func (*Attachment_DiffSet) isAttachment_Value() {}

func (*Attachment_DocumentContent) isAttachment_Value() {}

type ExecutedShellCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	CommandId     string                 `protobuf:"bytes,4,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutedShellCommand) Reset() {
	*x = ExecutedShellCommand{}
	mi := &file_attachment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutedShellCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedShellCommand) ProtoMessage() {}

func (x *ExecutedShellCommand) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedShellCommand.ProtoReflect.Descriptor instead.
func (*ExecutedShellCommand) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutedShellCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecutedShellCommand) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecutedShellCommand) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutedShellCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type RunningShellCommand struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Command       string                           `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Snapshot      *LongRunningShellCommandSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningShellCommand) Reset() {
	*x = RunningShellCommand{}
	mi := &file_attachment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningShellCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningShellCommand) ProtoMessage() {}

func (x *RunningShellCommand) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningShellCommand.ProtoReflect.Descriptor instead.
func (*RunningShellCommand) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{2}
}

func (x *RunningShellCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunningShellCommand) GetSnapshot() *LongRunningShellCommandSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type LongRunningShellCommandSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongRunningShellCommandSnapshot) Reset() {
	*x = LongRunningShellCommandSnapshot{}
	mi := &file_attachment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongRunningShellCommandSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongRunningShellCommandSnapshot) ProtoMessage() {}

func (x *LongRunningShellCommandSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongRunningShellCommandSnapshot.ProtoReflect.Descriptor instead.
func (*LongRunningShellCommandSnapshot) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{3}
}

func (x *LongRunningShellCommandSnapshot) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *LongRunningShellCommandSnapshot) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *LongRunningShellCommandSnapshot) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type DriveObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Types that are valid to be assigned to ObjectPayload:
	//
	//	*DriveObject_Workflow
	//	*DriveObject_Notebook
	//	*DriveObject_GenericStringObject
	ObjectPayload isDriveObject_ObjectPayload `protobuf_oneof:"object_payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriveObject) Reset() {
	*x = DriveObject{}
	mi := &file_attachment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriveObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriveObject) ProtoMessage() {}

func (x *DriveObject) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriveObject.ProtoReflect.Descriptor instead.
func (*DriveObject) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{4}
}

func (x *DriveObject) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DriveObject) GetObjectPayload() isDriveObject_ObjectPayload {
	if x != nil {
		return x.ObjectPayload
	}
	return nil
}

func (x *DriveObject) GetWorkflow() *Workflow {
	if x != nil {
		if x, ok := x.ObjectPayload.(*DriveObject_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *DriveObject) GetNotebook() *Notebook {
	if x != nil {
		if x, ok := x.ObjectPayload.(*DriveObject_Notebook); ok {
			return x.Notebook
		}
	}
	return nil
}

func (x *DriveObject) GetGenericStringObject() *GenericStringObject {
	if x != nil {
		if x, ok := x.ObjectPayload.(*DriveObject_GenericStringObject); ok {
			return x.GenericStringObject
		}
	}
	return nil
}

type isDriveObject_ObjectPayload interface {
	isDriveObject_ObjectPayload()
}

type DriveObject_Workflow struct {
	Workflow *Workflow `protobuf:"bytes,2,opt,name=workflow,proto3,oneof"`
}

type DriveObject_Notebook struct {
	Notebook *Notebook `protobuf:"bytes,3,opt,name=notebook,proto3,oneof"`
}

type DriveObject_GenericStringObject struct {
	GenericStringObject *GenericStringObject `protobuf:"bytes,4,opt,name=generic_string_object,json=genericStringObject,proto3,oneof"`
}

func (*DriveObject_Workflow) isDriveObject_ObjectPayload() {}

func (*DriveObject_Notebook) isDriveObject_ObjectPayload() {}

func (*DriveObject_GenericStringObject) isDriveObject_ObjectPayload() {}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_attachment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{5}
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Notebook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notebook) Reset() {
	*x = Notebook{}
	mi := &file_attachment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notebook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notebook) ProtoMessage() {}

func (x *Notebook) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notebook.ProtoReflect.Descriptor instead.
func (*Notebook) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{6}
}

func (x *Notebook) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notebook) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenericStringObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ObjectType    string                 `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericStringObject) Reset() {
	*x = GenericStringObject{}
	mi := &file_attachment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericStringObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericStringObject) ProtoMessage() {}

func (x *GenericStringObject) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericStringObject.ProtoReflect.Descriptor instead.
func (*GenericStringObject) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{7}
}

func (x *GenericStringObject) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *GenericStringObject) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

type DiffHunk struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	FilePath     string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineRange    *FileContentLineRange  `protobuf:"bytes,2,opt,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	DiffContent  string                 `protobuf:"bytes,3,opt,name=diff_content,json=diffContent,proto3" json:"diff_content,omitempty"`
	LinesAdded   uint32                 `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	LinesRemoved uint32                 `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	// Types that are valid to be assigned to Current:
	//
	//	*DiffHunk_CurrentBranchName
	//	*DiffHunk_CurrentHeadlessCommitSha
	Current isDiffHunk_Current `protobuf_oneof:"current"`
	// Types that are valid to be assigned to Base:
	//
	//	*DiffHunk_BaseBranchName
	//	*DiffHunk_BaseHeadlessCommitSha
	//	*DiffHunk_UncommittedChanges
	Base          isDiffHunk_Base `protobuf_oneof:"base"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffHunk) Reset() {
	*x = DiffHunk{}
	mi := &file_attachment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffHunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffHunk) ProtoMessage() {}

func (x *DiffHunk) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffHunk.ProtoReflect.Descriptor instead.
func (*DiffHunk) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{8}
}

func (x *DiffHunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DiffHunk) GetLineRange() *FileContentLineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

func (x *DiffHunk) GetDiffContent() string {
	if x != nil {
		return x.DiffContent
	}
	return ""
}

func (x *DiffHunk) GetLinesAdded() uint32 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *DiffHunk) GetLinesRemoved() uint32 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

func (x *DiffHunk) GetCurrent() isDiffHunk_Current {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *DiffHunk) GetCurrentBranchName() string {
	if x != nil {
		if x, ok := x.Current.(*DiffHunk_CurrentBranchName); ok {
			return x.CurrentBranchName
		}
	}
	return ""
}

func (x *DiffHunk) GetCurrentHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Current.(*DiffHunk_CurrentHeadlessCommitSha); ok {
			return x.CurrentHeadlessCommitSha
		}
	}
	return ""
}

func (x *DiffHunk) GetBase() isDiffHunk_Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DiffHunk) GetBaseBranchName() string {
	if x != nil {
		if x, ok := x.Base.(*DiffHunk_BaseBranchName); ok {
			return x.BaseBranchName
		}
	}
	return ""
}

func (x *DiffHunk) GetBaseHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Base.(*DiffHunk_BaseHeadlessCommitSha); ok {
			return x.BaseHeadlessCommitSha
		}
	}
	return ""
}

func (x *DiffHunk) GetUncommittedChanges() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Base.(*DiffHunk_UncommittedChanges); ok {
			return x.UncommittedChanges
		}
	}
	return nil
}

type isDiffHunk_Current interface {
	isDiffHunk_Current()
}

type DiffHunk_CurrentBranchName struct {
	CurrentBranchName string `protobuf:"bytes,6,opt,name=current_branch_name,json=currentBranchName,proto3,oneof"`
}

type DiffHunk_CurrentHeadlessCommitSha struct {
	CurrentHeadlessCommitSha string `protobuf:"bytes,7,opt,name=current_headless_commit_sha,json=currentHeadlessCommitSha,proto3,oneof"`
}

func (*DiffHunk_CurrentBranchName) isDiffHunk_Current() {}

func (*DiffHunk_CurrentHeadlessCommitSha) isDiffHunk_Current() {}

type isDiffHunk_Base interface {
	isDiffHunk_Base()
}

type DiffHunk_BaseBranchName struct {
	BaseBranchName string `protobuf:"bytes,8,opt,name=base_branch_name,json=baseBranchName,proto3,oneof"`
}

type DiffHunk_BaseHeadlessCommitSha struct {
	BaseHeadlessCommitSha string `protobuf:"bytes,9,opt,name=base_headless_commit_sha,json=baseHeadlessCommitSha,proto3,oneof"`
}

type DiffHunk_UncommittedChanges struct {
	UncommittedChanges *emptypb.Empty `protobuf:"bytes,10,opt,name=uncommitted_changes,json=uncommittedChanges,proto3,oneof"`
}

func (*DiffHunk_BaseBranchName) isDiffHunk_Base() {}

func (*DiffHunk_BaseHeadlessCommitSha) isDiffHunk_Base() {}

func (*DiffHunk_UncommittedChanges) isDiffHunk_Base() {}

type CurrentRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*CurrentRef_BranchName
	//	*CurrentRef_HeadlessCommitSha
	Ref           isCurrentRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentRef) Reset() {
	*x = CurrentRef{}
	mi := &file_attachment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentRef) ProtoMessage() {}

func (x *CurrentRef) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentRef.ProtoReflect.Descriptor instead.
func (*CurrentRef) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{9}
}

func (x *CurrentRef) GetRef() isCurrentRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *CurrentRef) GetBranchName() string {
	if x != nil {
		if x, ok := x.Ref.(*CurrentRef_BranchName); ok {
			return x.BranchName
		}
	}
	return ""
}

func (x *CurrentRef) GetHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Ref.(*CurrentRef_HeadlessCommitSha); ok {
			return x.HeadlessCommitSha
		}
	}
	return ""
}

type isCurrentRef_Ref interface {
	isCurrentRef_Ref()
}

type CurrentRef_BranchName struct {
	BranchName string `protobuf:"bytes,1,opt,name=branch_name,json=branchName,proto3,oneof"`
}

type CurrentRef_HeadlessCommitSha struct {
	HeadlessCommitSha string `protobuf:"bytes,2,opt,name=headless_commit_sha,json=headlessCommitSha,proto3,oneof"`
}

func (*CurrentRef_BranchName) isCurrentRef_Ref() {}

func (*CurrentRef_HeadlessCommitSha) isCurrentRef_Ref() {}

type BaseRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ref:
	//
	//	*BaseRef_BranchName
	//	*BaseRef_HeadlessCommitSha
	//	*BaseRef_UncommittedChanges
	Ref           isBaseRef_Ref `protobuf_oneof:"ref"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRef) Reset() {
	*x = BaseRef{}
	mi := &file_attachment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRef) ProtoMessage() {}

func (x *BaseRef) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRef.ProtoReflect.Descriptor instead.
func (*BaseRef) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{10}
}

func (x *BaseRef) GetRef() isBaseRef_Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *BaseRef) GetBranchName() string {
	if x != nil {
		if x, ok := x.Ref.(*BaseRef_BranchName); ok {
			return x.BranchName
		}
	}
	return ""
}

func (x *BaseRef) GetHeadlessCommitSha() string {
	if x != nil {
		if x, ok := x.Ref.(*BaseRef_HeadlessCommitSha); ok {
			return x.HeadlessCommitSha
		}
	}
	return ""
}

func (x *BaseRef) GetUncommittedChanges() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Ref.(*BaseRef_UncommittedChanges); ok {
			return x.UncommittedChanges
		}
	}
	return nil
}

type isBaseRef_Ref interface {
	isBaseRef_Ref()
}

type BaseRef_BranchName struct {
	BranchName string `protobuf:"bytes,1,opt,name=branch_name,json=branchName,proto3,oneof"`
}

type BaseRef_HeadlessCommitSha struct {
	HeadlessCommitSha string `protobuf:"bytes,2,opt,name=headless_commit_sha,json=headlessCommitSha,proto3,oneof"`
}

type BaseRef_UncommittedChanges struct {
	UncommittedChanges *emptypb.Empty `protobuf:"bytes,3,opt,name=uncommitted_changes,json=uncommittedChanges,proto3,oneof"`
}

func (*BaseRef_BranchName) isBaseRef_Ref() {}

func (*BaseRef_HeadlessCommitSha) isBaseRef_Ref() {}

func (*BaseRef_UncommittedChanges) isBaseRef_Ref() {}

type DiffSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hunks         []*DiffSet_DiffHunk    `protobuf:"bytes,1,rep,name=hunks,proto3" json:"hunks,omitempty"`
	CurrRef       *CurrentRef            `protobuf:"bytes,2,opt,name=curr_ref,json=currRef,proto3" json:"curr_ref,omitempty"`
	BaseRef       *BaseRef               `protobuf:"bytes,3,opt,name=base_ref,json=baseRef,proto3" json:"base_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffSet) Reset() {
	*x = DiffSet{}
	mi := &file_attachment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffSet) ProtoMessage() {}

func (x *DiffSet) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffSet.ProtoReflect.Descriptor instead.
func (*DiffSet) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{11}
}

func (x *DiffSet) GetHunks() []*DiffSet_DiffHunk {
	if x != nil {
		return x.Hunks
	}
	return nil
}

func (x *DiffSet) GetCurrRef() *CurrentRef {
	if x != nil {
		return x.CurrRef
	}
	return nil
}

func (x *DiffSet) GetBaseRef() *BaseRef {
	if x != nil {
		return x.BaseRef
	}
	return nil
}

type DiffSet_DiffHunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineRange     *FileContentLineRange  `protobuf:"bytes,2,opt,name=line_range,json=lineRange,proto3" json:"line_range,omitempty"`
	DiffContent   string                 `protobuf:"bytes,3,opt,name=diff_content,json=diffContent,proto3" json:"diff_content,omitempty"`
	LinesAdded    uint32                 `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	LinesRemoved  uint32                 `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffSet_DiffHunk) Reset() {
	*x = DiffSet_DiffHunk{}
	mi := &file_attachment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffSet_DiffHunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffSet_DiffHunk) ProtoMessage() {}

func (x *DiffSet_DiffHunk) ProtoReflect() protoreflect.Message {
	mi := &file_attachment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffSet_DiffHunk.ProtoReflect.Descriptor instead.
func (*DiffSet_DiffHunk) Descriptor() ([]byte, []int) {
	return file_attachment_proto_rawDescGZIP(), []int{11, 0}
}

func (x *DiffSet_DiffHunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DiffSet_DiffHunk) GetLineRange() *FileContentLineRange {
	if x != nil {
		return x.LineRange
	}
	return nil
}

func (x *DiffSet_DiffHunk) GetDiffContent() string {
	if x != nil {
		return x.DiffContent
	}
	return ""
}

func (x *DiffSet_DiffHunk) GetLinesAdded() uint32 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *DiffSet_DiffHunk) GetLinesRemoved() uint32 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

var File_attachment_proto protoreflect.FileDescriptor

const file_attachment_proto_rawDesc = "" +
	"\n" +
	"\x10attachment.proto\x12\x13warp.multi_agent.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16document_content.proto\x1a\roptions.proto\x1a\x12file_content.proto\"\x8c\x04\n" +
	"\n" +
	"Attachment\x12\x1f\n" +
	"\n" +
	"plain_text\x18\x01 \x01(\tH\x00R\tplainText\x12a\n" +
	"\x16executed_shell_command\x18\x02 \x01(\v2).warp.multi_agent.v1.ExecutedShellCommandH\x00R\x14executedShellCommand\x12^\n" +
	"\x15running_shell_command\x18\x03 \x01(\v2(.warp.multi_agent.v1.RunningShellCommandH\x00R\x13runningShellCommand\x12E\n" +
	"\fdrive_object\x18\x04 \x01(\v2 .warp.multi_agent.v1.DriveObjectH\x00R\vdriveObject\x12<\n" +
	"\tdiff_hunk\x18\x05 \x01(\v2\x1d.warp.multi_agent.v1.DiffHunkH\x00R\bdiffHunk\x129\n" +
	"\bdiff_set\x18\x06 \x01(\v2\x1c.warp.multi_agent.v1.DiffSetH\x00R\adiffSet\x12Q\n" +
	"\x10document_content\x18\a \x01(\v2$.warp.multi_agent.v1.DocumentContentH\x00R\x0fdocumentContentB\a\n" +
	"\x05value\"\x84\x01\n" +
	"\x14ExecutedShellCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"command_id\x18\x04 \x01(\tR\tcommandId\"\x81\x01\n" +
	"\x13RunningShellCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12P\n" +
	"\bsnapshot\x18\x02 \x01(\v24.warp.multi_agent.v1.LongRunningShellCommandSnapshotR\bsnapshot\"p\n" +
	"\x1fLongRunningShellCommandSnapshot\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\"\x8b\x02\n" +
	"\vDriveObject\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12;\n" +
	"\bworkflow\x18\x02 \x01(\v2\x1d.warp.multi_agent.v1.WorkflowH\x00R\bworkflow\x12;\n" +
	"\bnotebook\x18\x03 \x01(\v2\x1d.warp.multi_agent.v1.NotebookH\x00R\bnotebook\x12^\n" +
	"\x15generic_string_object\x18\x04 \x01(\v2(.warp.multi_agent.v1.GenericStringObjectH\x00R\x13genericStringObjectB\x10\n" +
	"\x0eobject_payload\"Z\n" +
	"\bWorkflow\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\":\n" +
	"\bNotebook\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"P\n" +
	"\x13GenericStringObject\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\tR\n" +
	"objectType\"\x92\x04\n" +
	"\bDiffHunk\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12H\n" +
	"\n" +
	"line_range\x18\x02 \x01(\v2).warp.multi_agent.v1.FileContentLineRangeR\tlineRange\x12!\n" +
	"\fdiff_content\x18\x03 \x01(\tR\vdiffContent\x12\x1f\n" +
	"\vlines_added\x18\x04 \x01(\rR\n" +
	"linesAdded\x12#\n" +
	"\rlines_removed\x18\x05 \x01(\rR\flinesRemoved\x120\n" +
	"\x13current_branch_name\x18\x06 \x01(\tH\x00R\x11currentBranchName\x12?\n" +
	"\x1bcurrent_headless_commit_sha\x18\a \x01(\tH\x00R\x18currentHeadlessCommitSha\x12*\n" +
	"\x10base_branch_name\x18\b \x01(\tH\x01R\x0ebaseBranchName\x129\n" +
	"\x18base_headless_commit_sha\x18\t \x01(\tH\x01R\x15baseHeadlessCommitSha\x12I\n" +
	"\x13uncommitted_changes\x18\n" +
	" \x01(\v2\x16.google.protobuf.EmptyH\x01R\x12uncommittedChangesB\t\n" +
	"\acurrentB\x06\n" +
	"\x04base\"h\n" +
	"\n" +
	"CurrentRef\x12!\n" +
	"\vbranch_name\x18\x01 \x01(\tH\x00R\n" +
	"branchName\x120\n" +
	"\x13headless_commit_sha\x18\x02 \x01(\tH\x00R\x11headlessCommitShaB\x05\n" +
	"\x03ref\"\xb0\x01\n" +
	"\aBaseRef\x12!\n" +
	"\vbranch_name\x18\x01 \x01(\tH\x00R\n" +
	"branchName\x120\n" +
	"\x13headless_commit_sha\x18\x02 \x01(\tH\x00R\x11headlessCommitSha\x12I\n" +
	"\x13uncommitted_changes\x18\x03 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x12uncommittedChangesB\x05\n" +
	"\x03ref\"\x98\x03\n" +
	"\aDiffSet\x12;\n" +
	"\x05hunks\x18\x01 \x03(\v2%.warp.multi_agent.v1.DiffSet.DiffHunkR\x05hunks\x12:\n" +
	"\bcurr_ref\x18\x02 \x01(\v2\x1f.warp.multi_agent.v1.CurrentRefR\acurrRef\x127\n" +
	"\bbase_ref\x18\x03 \x01(\v2\x1c.warp.multi_agent.v1.BaseRefR\abaseRef\x1a\xda\x01\n" +
	"\bDiffHunk\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12H\n" +
	"\n" +
	"line_range\x18\x02 \x01(\v2).warp.multi_agent.v1.FileContentLineRangeR\tlineRange\x12!\n" +
	"\fdiff_content\x18\x03 \x01(\tR\vdiffContent\x12\x1f\n" +
	"\vlines_added\x18\x04 \x01(\rR\n" +
	"linesAdded\x12#\n" +
	"\rlines_removed\x18\x05 \x01(\rR\flinesRemovedB\x1aZ\x18kiro-go/internal/warp/pbb\x06proto3"

var (
	file_attachment_proto_rawDescOnce sync.Once
	file_attachment_proto_rawDescData []byte
)

func file_attachment_proto_rawDescGZIP() []byte {
	file_attachment_proto_rawDescOnce.Do(func() {
		file_attachment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)))
	})
	return file_attachment_proto_rawDescData
}

var file_attachment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_attachment_proto_goTypes = []any{
	(*Attachment)(nil),                      // 0: warp.multi_agent.v1.Attachment
	(*ExecutedShellCommand)(nil),            // 1: warp.multi_agent.v1.ExecutedShellCommand
	(*RunningShellCommand)(nil),             // 2: warp.multi_agent.v1.RunningShellCommand
	(*LongRunningShellCommandSnapshot)(nil), // 3: warp.multi_agent.v1.LongRunningShellCommandSnapshot
	(*DriveObject)(nil),                     // 4: warp.multi_agent.v1.DriveObject
	(*Workflow)(nil),                        // 5: warp.multi_agent.v1.Workflow
	(*Notebook)(nil),                        // 6: warp.multi_agent.v1.Notebook
	(*GenericStringObject)(nil),             // 7: warp.multi_agent.v1.GenericStringObject
	(*DiffHunk)(nil),                        // 8: warp.multi_agent.v1.DiffHunk
	(*CurrentRef)(nil),                      // 9: warp.multi_agent.v1.CurrentRef
	(*BaseRef)(nil),                         // 10: warp.multi_agent.v1.BaseRef
	(*DiffSet)(nil),                         // 11: warp.multi_agent.v1.DiffSet
	(*DiffSet_DiffHunk)(nil),                // 12: warp.multi_agent.v1.DiffSet.DiffHunk
	(*DocumentContent)(nil),                 // 13: warp.multi_agent.v1.DocumentContent
	(*FileContentLineRange)(nil),            // 14: warp.multi_agent.v1.FileContentLineRange
	(*emptypb.Empty)(nil),                   // 15: google.protobuf.Empty
}
var file_attachment_proto_depIdxs = []int32{
	1,  // 0: warp.multi_agent.v1.Attachment.executed_shell_command:type_name -> warp.multi_agent.v1.ExecutedShellCommand
	2,  // 1: warp.multi_agent.v1.Attachment.running_shell_command:type_name -> warp.multi_agent.v1.RunningShellCommand
	4,  // 2: warp.multi_agent.v1.Attachment.drive_object:type_name -> warp.multi_agent.v1.DriveObject
	8,  // 3: warp.multi_agent.v1.Attachment.diff_hunk:type_name -> warp.multi_agent.v1.DiffHunk
	11, // 4: warp.multi_agent.v1.Attachment.diff_set:type_name -> warp.multi_agent.v1.DiffSet
	13, // 5: warp.multi_agent.v1.Attachment.document_content:type_name -> warp.multi_agent.v1.DocumentContent
	3,  // 6: warp.multi_agent.v1.RunningShellCommand.snapshot:type_name -> warp.multi_agent.v1.LongRunningShellCommandSnapshot
	5,  // 7: warp.multi_agent.v1.DriveObject.workflow:type_name -> warp.multi_agent.v1.Workflow
	6,  // 8: warp.multi_agent.v1.DriveObject.notebook:type_name -> warp.multi_agent.v1.Notebook
	7,  // 9: warp.multi_agent.v1.DriveObject.generic_string_object:type_name -> warp.multi_agent.v1.GenericStringObject
	14, // 10: warp.multi_agent.v1.DiffHunk.line_range:type_name -> warp.multi_agent.v1.FileContentLineRange
	15, // 11: warp.multi_agent.v1.DiffHunk.uncommitted_changes:type_name -> google.protobuf.Empty
	15, // 12: warp.multi_agent.v1.BaseRef.uncommitted_changes:type_name -> google.protobuf.Empty
	12, // 13: warp.multi_agent.v1.DiffSet.hunks:type_name -> warp.multi_agent.v1.DiffSet.DiffHunk
	9,  // 14: warp.multi_agent.v1.DiffSet.curr_ref:type_name -> warp.multi_agent.v1.CurrentRef
	10, // 15: warp.multi_agent.v1.DiffSet.base_ref:type_name -> warp.multi_agent.v1.BaseRef
	14, // 16: warp.multi_agent.v1.DiffSet.DiffHunk.line_range:type_name -> warp.multi_agent.v1.FileContentLineRange
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_attachment_proto_init() }
func file_attachment_proto_init() {
	if File_attachment_proto != nil {
		return
	}
	file_document_content_proto_init()
	file_options_proto_init()
	file_file_content_proto_init()
	file_attachment_proto_msgTypes[0].OneofWrappers = []any{
		(*Attachment_PlainText)(nil),
		(*Attachment_ExecutedShellCommand)(nil),
		(*Attachment_RunningShellCommand)(nil),
		(*Attachment_DriveObject)(nil),
		(*Attachment_DiffHunk)(nil),
		(*Attachment_DiffSet)(nil),
		(*Attachment_DocumentContent)(nil),
	}
	file_attachment_proto_msgTypes[4].OneofWrappers = []any{
		(*DriveObject_Workflow)(nil),
		(*DriveObject_Notebook)(nil),
		(*DriveObject_GenericStringObject)(nil),
	}
	file_attachment_proto_msgTypes[8].OneofWrappers = []any{
		(*DiffHunk_CurrentBranchName)(nil),
		(*DiffHunk_CurrentHeadlessCommitSha)(nil),
		(*DiffHunk_BaseBranchName)(nil),
		(*DiffHunk_BaseHeadlessCommitSha)(nil),
		(*DiffHunk_UncommittedChanges)(nil),
	}
	file_attachment_proto_msgTypes[9].OneofWrappers = []any{
		(*CurrentRef_BranchName)(nil),
		(*CurrentRef_HeadlessCommitSha)(nil),
	}
	file_attachment_proto_msgTypes[10].OneofWrappers = []any{
		(*BaseRef_BranchName)(nil),
		(*BaseRef_HeadlessCommitSha)(nil),
		(*BaseRef_UncommittedChanges)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attachment_proto_rawDesc), len(file_attachment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attachment_proto_goTypes,
		DependencyIndexes: file_attachment_proto_depIdxs,
		MessageInfos:      file_attachment_proto_msgTypes,
	}.Build()
	File_attachment_proto = out.File
	file_attachment_proto_goTypes = nil
	file_attachment_proto_depIdxs = nil
}
