// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: input_context.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputContext struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	Directory             *InputContext_Directory       `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	OperatingSystem       *InputContext_OperatingSystem `protobuf:"bytes,2,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Shell                 *InputContext_Shell           `protobuf:"bytes,3,opt,name=shell,proto3" json:"shell,omitempty"`
	CurrentTime           *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	Codebases             []*InputContext_Codebase      `protobuf:"bytes,8,rep,name=codebases,proto3" json:"codebases,omitempty"`
	ProjectRules          []*InputContext_ProjectRules  `protobuf:"bytes,10,rep,name=project_rules,json=projectRules,proto3" json:"project_rules,omitempty"`
	Git                   *InputContext_Git             `protobuf:"bytes,11,opt,name=git,proto3" json:"git,omitempty"`
	ExecutedShellCommands []*ExecutedShellCommand       `protobuf:"bytes,5,rep,name=executed_shell_commands,json=executedShellCommands,proto3" json:"executed_shell_commands,omitempty"`
	SelectedText          []*InputContext_SelectedText  `protobuf:"bytes,6,rep,name=selected_text,json=selectedText,proto3" json:"selected_text,omitempty"`
	Images                []*InputContext_Image         `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	Files                 []*InputContext_File          `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InputContext) Reset() {
	*x = InputContext{}
	mi := &file_input_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext) ProtoMessage() {}

func (x *InputContext) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext.ProtoReflect.Descriptor instead.
func (*InputContext) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0}
}

func (x *InputContext) GetDirectory() *InputContext_Directory {
	if x != nil {
		return x.Directory
	}
	return nil
}

func (x *InputContext) GetOperatingSystem() *InputContext_OperatingSystem {
	if x != nil {
		return x.OperatingSystem
	}
	return nil
}

func (x *InputContext) GetShell() *InputContext_Shell {
	if x != nil {
		return x.Shell
	}
	return nil
}

func (x *InputContext) GetCurrentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentTime
	}
	return nil
}

func (x *InputContext) GetCodebases() []*InputContext_Codebase {
	if x != nil {
		return x.Codebases
	}
	return nil
}

func (x *InputContext) GetProjectRules() []*InputContext_ProjectRules {
	if x != nil {
		return x.ProjectRules
	}
	return nil
}

func (x *InputContext) GetGit() *InputContext_Git {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *InputContext) GetExecutedShellCommands() []*ExecutedShellCommand {
	if x != nil {
		return x.ExecutedShellCommands
	}
	return nil
}

func (x *InputContext) GetSelectedText() []*InputContext_SelectedText {
	if x != nil {
		return x.SelectedText
	}
	return nil
}

func (x *InputContext) GetImages() []*InputContext_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *InputContext) GetFiles() []*InputContext_File {
	if x != nil {
		return x.Files
	}
	return nil
}

type InputContext_SelectedText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_SelectedText) Reset() {
	*x = InputContext_SelectedText{}
	mi := &file_input_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_SelectedText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_SelectedText) ProtoMessage() {}

func (x *InputContext_SelectedText) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_SelectedText.ProtoReflect.Descriptor instead.
func (*InputContext_SelectedText) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InputContext_SelectedText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type InputContext_Directory struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Pwd                   string                 `protobuf:"bytes,1,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Home                  string                 `protobuf:"bytes,2,opt,name=home,proto3" json:"home,omitempty"`
	PwdFileSymbolsIndexed bool                   `protobuf:"varint,3,opt,name=pwd_file_symbols_indexed,json=pwdFileSymbolsIndexed,proto3" json:"pwd_file_symbols_indexed,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InputContext_Directory) Reset() {
	*x = InputContext_Directory{}
	mi := &file_input_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Directory) ProtoMessage() {}

func (x *InputContext_Directory) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Directory.ProtoReflect.Descriptor instead.
func (*InputContext_Directory) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 1}
}

func (x *InputContext_Directory) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *InputContext_Directory) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

func (x *InputContext_Directory) GetPwdFileSymbolsIndexed() bool {
	if x != nil {
		return x.PwdFileSymbolsIndexed
	}
	return false
}

type InputContext_Shell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Shell) Reset() {
	*x = InputContext_Shell{}
	mi := &file_input_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Shell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Shell) ProtoMessage() {}

func (x *InputContext_Shell) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Shell.ProtoReflect.Descriptor instead.
func (*InputContext_Shell) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 2}
}

func (x *InputContext_Shell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputContext_Shell) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InputContext_OperatingSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Distribution  string                 `protobuf:"bytes,2,opt,name=distribution,proto3" json:"distribution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_OperatingSystem) Reset() {
	*x = InputContext_OperatingSystem{}
	mi := &file_input_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_OperatingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_OperatingSystem) ProtoMessage() {}

func (x *InputContext_OperatingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_OperatingSystem.ProtoReflect.Descriptor instead.
func (*InputContext_OperatingSystem) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 3}
}

func (x *InputContext_OperatingSystem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *InputContext_OperatingSystem) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

type InputContext_Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Image) Reset() {
	*x = InputContext_Image{}
	mi := &file_input_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Image) ProtoMessage() {}

func (x *InputContext_Image) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Image.ProtoReflect.Descriptor instead.
func (*InputContext_Image) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 4}
}

func (x *InputContext_Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InputContext_Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type InputContext_Codebase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Codebase) Reset() {
	*x = InputContext_Codebase{}
	mi := &file_input_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Codebase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Codebase) ProtoMessage() {}

func (x *InputContext_Codebase) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Codebase.ProtoReflect.Descriptor instead.
func (*InputContext_Codebase) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 5}
}

func (x *InputContext_Codebase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InputContext_Codebase) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type InputContext_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *FileContent           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_File) Reset() {
	*x = InputContext_File{}
	mi := &file_input_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_File) ProtoMessage() {}

func (x *InputContext_File) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_File.ProtoReflect.Descriptor instead.
func (*InputContext_File) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 6}
}

func (x *InputContext_File) GetContent() *FileContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type InputContext_ProjectRules struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RootPath                string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	ActiveRuleFiles         []*FileContent         `protobuf:"bytes,2,rep,name=active_rule_files,json=activeRuleFiles,proto3" json:"active_rule_files,omitempty"`
	AdditionalRuleFilePaths []string               `protobuf:"bytes,3,rep,name=additional_rule_file_paths,json=additionalRuleFilePaths,proto3" json:"additional_rule_file_paths,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InputContext_ProjectRules) Reset() {
	*x = InputContext_ProjectRules{}
	mi := &file_input_context_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_ProjectRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_ProjectRules) ProtoMessage() {}

func (x *InputContext_ProjectRules) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_ProjectRules.ProtoReflect.Descriptor instead.
func (*InputContext_ProjectRules) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 7}
}

func (x *InputContext_ProjectRules) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *InputContext_ProjectRules) GetActiveRuleFiles() []*FileContent {
	if x != nil {
		return x.ActiveRuleFiles
	}
	return nil
}

func (x *InputContext_ProjectRules) GetAdditionalRuleFilePaths() []string {
	if x != nil {
		return x.AdditionalRuleFilePaths
	}
	return nil
}

type InputContext_Git struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          string                 `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputContext_Git) Reset() {
	*x = InputContext_Git{}
	mi := &file_input_context_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputContext_Git) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputContext_Git) ProtoMessage() {}

func (x *InputContext_Git) ProtoReflect() protoreflect.Message {
	mi := &file_input_context_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputContext_Git.ProtoReflect.Descriptor instead.
func (*InputContext_Git) Descriptor() ([]byte, []int) {
	return file_input_context_proto_rawDescGZIP(), []int{0, 8}
}

func (x *InputContext_Git) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

var File_input_context_proto protoreflect.FileDescriptor

const file_input_context_proto_rawDesc = "" +
	"\n" +
	"\x13input_context.proto\x12\x13warp.multi_agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12file_content.proto\x1a\x10attachment.proto\x1a\roptions.proto\"\xe4\v\n" +
	"\fInputContext\x12I\n" +
	"\tdirectory\x18\x01 \x01(\v2+.warp.multi_agent.v1.InputContext.DirectoryR\tdirectory\x12\\\n" +
	"\x10operating_system\x18\x02 \x01(\v21.warp.multi_agent.v1.InputContext.OperatingSystemR\x0foperatingSystem\x12=\n" +
	"\x05shell\x18\x03 \x01(\v2'.warp.multi_agent.v1.InputContext.ShellR\x05shell\x12=\n" +
	"\fcurrent_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcurrentTime\x12H\n" +
	"\tcodebases\x18\b \x03(\v2*.warp.multi_agent.v1.InputContext.CodebaseR\tcodebases\x12S\n" +
	"\rproject_rules\x18\n" +
	" \x03(\v2..warp.multi_agent.v1.InputContext.ProjectRulesR\fprojectRules\x127\n" +
	"\x03git\x18\v \x01(\v2%.warp.multi_agent.v1.InputContext.GitR\x03git\x12a\n" +
	"\x17executed_shell_commands\x18\x05 \x03(\v2).warp.multi_agent.v1.ExecutedShellCommandR\x15executedShellCommands\x12S\n" +
	"\rselected_text\x18\x06 \x03(\v2..warp.multi_agent.v1.InputContext.SelectedTextR\fselectedText\x12?\n" +
	"\x06images\x18\a \x03(\v2'.warp.multi_agent.v1.InputContext.ImageR\x06images\x12<\n" +
	"\x05files\x18\t \x03(\v2&.warp.multi_agent.v1.InputContext.FileR\x05files\x1a\"\n" +
	"\fSelectedText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x1aj\n" +
	"\tDirectory\x12\x10\n" +
	"\x03pwd\x18\x01 \x01(\tR\x03pwd\x12\x12\n" +
	"\x04home\x18\x02 \x01(\tR\x04home\x127\n" +
	"\x18pwd_file_symbols_indexed\x18\x03 \x01(\bR\x15pwdFileSymbolsIndexed\x1a5\n" +
	"\x05Shell\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x1aQ\n" +
	"\x0fOperatingSystem\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\"\n" +
	"\fdistribution\x18\x02 \x01(\tR\fdistribution\x1a8\n" +
	"\x05Image\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x1a2\n" +
	"\bCodebase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x1aB\n" +
	"\x04File\x12:\n" +
	"\acontent\x18\x01 \x01(\v2 .warp.multi_agent.v1.FileContentR\acontent\x1a\xb6\x01\n" +
	"\fProjectRules\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12L\n" +
	"\x11active_rule_files\x18\x02 \x03(\v2 .warp.multi_agent.v1.FileContentR\x0factiveRuleFiles\x12;\n" +
	"\x1aadditional_rule_file_paths\x18\x03 \x03(\tR\x17additionalRuleFilePaths\x1a\x19\n" +
	"\x03Git\x12\x12\n" +
	"\x04head\x18\x01 \x01(\tR\x04headB\x1aZ\x18kiro-go/internal/warp/pbb\x06proto3"

var (
	file_input_context_proto_rawDescOnce sync.Once
	file_input_context_proto_rawDescData []byte
)

func file_input_context_proto_rawDescGZIP() []byte {
	file_input_context_proto_rawDescOnce.Do(func() {
		file_input_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_input_context_proto_rawDesc), len(file_input_context_proto_rawDesc)))
	})
	return file_input_context_proto_rawDescData
}

var file_input_context_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_input_context_proto_goTypes = []any{
	(*InputContext)(nil),                 // 0: warp.multi_agent.v1.InputContext
	(*InputContext_SelectedText)(nil),    // 1: warp.multi_agent.v1.InputContext.SelectedText
	(*InputContext_Directory)(nil),       // 2: warp.multi_agent.v1.InputContext.Directory
	(*InputContext_Shell)(nil),           // 3: warp.multi_agent.v1.InputContext.Shell
	(*InputContext_OperatingSystem)(nil), // 4: warp.multi_agent.v1.InputContext.OperatingSystem
	(*InputContext_Image)(nil),           // 5: warp.multi_agent.v1.InputContext.Image
	(*InputContext_Codebase)(nil),        // 6: warp.multi_agent.v1.InputContext.Codebase
	(*InputContext_File)(nil),            // 7: warp.multi_agent.v1.InputContext.File
	(*InputContext_ProjectRules)(nil),    // 8: warp.multi_agent.v1.InputContext.ProjectRules
	(*InputContext_Git)(nil),             // 9: warp.multi_agent.v1.InputContext.Git
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
	(*ExecutedShellCommand)(nil),         // 11: warp.multi_agent.v1.ExecutedShellCommand
	(*FileContent)(nil),                  // 12: warp.multi_agent.v1.FileContent
}
var file_input_context_proto_depIdxs = []int32{
	2,  // 0: warp.multi_agent.v1.InputContext.directory:type_name -> warp.multi_agent.v1.InputContext.Directory
	4,  // 1: warp.multi_agent.v1.InputContext.operating_system:type_name -> warp.multi_agent.v1.InputContext.OperatingSystem
	3,  // 2: warp.multi_agent.v1.InputContext.shell:type_name -> warp.multi_agent.v1.InputContext.Shell
	10, // 3: warp.multi_agent.v1.InputContext.current_time:type_name -> google.protobuf.Timestamp
	6,  // 4: warp.multi_agent.v1.InputContext.codebases:type_name -> warp.multi_agent.v1.InputContext.Codebase
	8,  // 5: warp.multi_agent.v1.InputContext.project_rules:type_name -> warp.multi_agent.v1.InputContext.ProjectRules
	9,  // 6: warp.multi_agent.v1.InputContext.git:type_name -> warp.multi_agent.v1.InputContext.Git
	11, // 7: warp.multi_agent.v1.InputContext.executed_shell_commands:type_name -> warp.multi_agent.v1.ExecutedShellCommand
	1,  // 8: warp.multi_agent.v1.InputContext.selected_text:type_name -> warp.multi_agent.v1.InputContext.SelectedText
	5,  // 9: warp.multi_agent.v1.InputContext.images:type_name -> warp.multi_agent.v1.InputContext.Image
	7,  // 10: warp.multi_agent.v1.InputContext.files:type_name -> warp.multi_agent.v1.InputContext.File
	12, // 11: warp.multi_agent.v1.InputContext.File.content:type_name -> warp.multi_agent.v1.FileContent
	12, // 12: warp.multi_agent.v1.InputContext.ProjectRules.active_rule_files:type_name -> warp.multi_agent.v1.FileContent
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_input_context_proto_init() }
func file_input_context_proto_init() {
	if File_input_context_proto != nil {
		return
	}
	file_file_content_proto_init()
	file_attachment_proto_init()
	file_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_input_context_proto_rawDesc), len(file_input_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_input_context_proto_goTypes,
		DependencyIndexes: file_input_context_proto_depIdxs,
		MessageInfos:      file_input_context_proto_msgTypes,
	}.Build()
	File_input_context_proto = out.File
	file_input_context_proto_goTypes = nil
	file_input_context_proto_depIdxs = nil
}
