// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Activate(arg1:string):Promise<string>;

export function AddAccountByIdC(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Account>;

export function AddAccountByIdCWithProvider(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Account>;

export function AddAccountBySocial(arg1:string,arg2:string):Promise<main.Account>;

export function ApplyPromptToClaudeCode(arg1:string):Promise<void>;

export function ApplyPromptToCursorRules(arg1:string,arg2:string):Promise<void>;

export function BatchDeleteAccounts(arg1:Array<string>):Promise<number>;

export function CheckActivation():Promise<main.ActivationData>;

export function ClearCredentials():Promise<string>;

export function ClearExternalTunnel():Promise<string>;

export function ClearLogFile():Promise<void>;

export function ClearProxyLogs():Promise<void>;

export function Deactivate():Promise<string>;

export function DeleteAccount(arg1:string):Promise<string>;

export function DeletePromptTemplate(arg1:string):Promise<void>;

export function EnsureFactoryApiKey():Promise<string>;

export function ExportAccounts(arg1:Array<string>):Promise<string>;

export function ExportAccountsToFile(arg1:Array<string>):Promise<string>;

export function ExportCredsToShellRC(arg1:string):Promise<void>;

export function GenerateCredsKey():Promise<string>;

export function GenerateCredsKeyFromKeychain():Promise<string>;

export function GenerateRelayKey(arg1:string):Promise<string>;

export function GenerateRelayKeyFromKeychain(arg1:string):Promise<string>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetBackend():Promise<string>;

export function GetConfig():Promise<main.ProxyConfig>;

export function GetCredentialsInfo():Promise<main.CredentialsInfo>;

export function GetDataDirPath():Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetPromptTemplates():Promise<Array<main.PromptTemplate>>;

export function GetProxyLogs():Promise<Array<string>>;

export function GetRecentLogs(arg1:number):Promise<string>;

export function GetServerSyncConfig():Promise<main.ServerSyncConfig>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetTunnelStatus():Promise<main.TunnelStatus>;

export function GetWarpCredentialFromKeychain():Promise<Record<string, string>>;

export function ImportCredentials(arg1:string):Promise<string>;

export function ImportLocalAccount():Promise<main.Account>;

export function ImportWarpCredentialFromKeychain():Promise<string>;

export function ListKeychainSources():Promise<Array<main.KeychainSource>>;

export function LoadTunnelConfig():Promise<main.TunnelConfig>;

export function OneClickStart():Promise<string>;

export function OpenDataDir():Promise<string>;

export function ReadClaudeCodeSettings():Promise<Record<string, any>>;

export function ReadCredentialsRaw():Promise<string>;

export function ReadDroidSettings():Promise<Record<string, any>>;

export function ReadFactoryConfig():Promise<Record<string, any>>;

export function ReadOpenCodeConfig():Promise<Record<string, any>>;

export function RefreshNow():Promise<string>;

export function SaveAccountsToFile(arg1:string,arg2:string):Promise<void>;

export function SaveClaudeCodeConfig(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SaveCredentialsRaw(arg1:string):Promise<string>;

export function SavePromptTemplate(arg1:main.PromptTemplate):Promise<void>;

export function SaveServerSyncConfig(arg1:string,arg2:string):Promise<void>;

export function SaveTunnelConfig(arg1:main.TunnelConfig):Promise<string>;

export function SetBackend(arg1:string):Promise<string>;

export function SetExternalTunnel(arg1:string):Promise<string>;

export function StartProxy():Promise<string>;

export function StartTunnel():Promise<string>;

export function StopProxy():Promise<string>;

export function StopTunnel():Promise<string>;

export function SwitchAccount(arg1:string):Promise<string>;

export function SyncAccount(arg1:string):Promise<main.Account>;

export function TestServerConnection(arg1:string):Promise<string>;

export function UpdateAccount(arg1:string,arg2:any,arg3:any,arg4:any,arg5:any,arg6:any):Promise<main.Account>;

export function UpdateAccountLabel(arg1:string,arg2:string):Promise<main.Account>;

export function UploadCredentialsToServer(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UseKeychainSource(arg1:string):Promise<string>;

export function WriteClaudeCodeSettings(arg1:Record<string, any>):Promise<string>;

export function WriteDroidSettings(arg1:Record<string, any>):Promise<string>;

export function WriteFactoryConfig(arg1:Record<string, any>):Promise<string>;

export function WriteOpenCodeConfig(arg1:Record<string, any>):Promise<string>;
