// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function AddAccountByIdC(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAccountByIdC'](arg1, arg2, arg3, arg4);
}

export function AddAccountByIdCWithProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddAccountByIdCWithProvider'](arg1, arg2, arg3, arg4, arg5);
}

export function AddAccountBySocial(arg1, arg2) {
  return window['go']['main']['App']['AddAccountBySocial'](arg1, arg2);
}

export function ApplyPromptToClaudeCode(arg1) {
  return window['go']['main']['App']['ApplyPromptToClaudeCode'](arg1);
}

export function ApplyPromptToCursorRules(arg1, arg2) {
  return window['go']['main']['App']['ApplyPromptToCursorRules'](arg1, arg2);
}

export function BatchDeleteAccounts(arg1) {
  return window['go']['main']['App']['BatchDeleteAccounts'](arg1);
}

export function CheckActivation() {
  return window['go']['main']['App']['CheckActivation']();
}

export function ClearCredentials() {
  return window['go']['main']['App']['ClearCredentials']();
}

export function ClearExternalTunnel() {
  return window['go']['main']['App']['ClearExternalTunnel']();
}

export function Deactivate() {
  return window['go']['main']['App']['Deactivate']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['main']['App']['DeletePromptTemplate'](arg1);
}

export function EnsureFactoryApiKey() {
  return window['go']['main']['App']['EnsureFactoryApiKey']();
}

export function ExportAccounts(arg1) {
  return window['go']['main']['App']['ExportAccounts'](arg1);
}

export function ExportAccountsToFile(arg1) {
  return window['go']['main']['App']['ExportAccountsToFile'](arg1);
}

export function ExportCredsToShellRC(arg1) {
  return window['go']['main']['App']['ExportCredsToShellRC'](arg1);
}

export function GenerateCredsKey() {
  return window['go']['main']['App']['GenerateCredsKey']();
}

export function GenerateCredsKeyFromKeychain() {
  return window['go']['main']['App']['GenerateCredsKeyFromKeychain']();
}

export function GenerateRelayKey(arg1) {
  return window['go']['main']['App']['GenerateRelayKey'](arg1);
}

export function GenerateRelayKeyFromKeychain(arg1) {
  return window['go']['main']['App']['GenerateRelayKeyFromKeychain'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCredentialsInfo() {
  return window['go']['main']['App']['GetCredentialsInfo']();
}

export function GetDataDirPath() {
  return window['go']['main']['App']['GetDataDirPath']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetPromptTemplates() {
  return window['go']['main']['App']['GetPromptTemplates']();
}

export function GetProxyLogs() {
  return window['go']['main']['App']['GetProxyLogs']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetServerSyncConfig() {
  return window['go']['main']['App']['GetServerSyncConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTunnelStatus() {
  return window['go']['main']['App']['GetTunnelStatus']();
}

export function ImportCredentials(arg1) {
  return window['go']['main']['App']['ImportCredentials'](arg1);
}

export function ImportLocalAccount() {
  return window['go']['main']['App']['ImportLocalAccount']();
}

export function ListKeychainSources() {
  return window['go']['main']['App']['ListKeychainSources']();
}

export function LoadTunnelConfig() {
  return window['go']['main']['App']['LoadTunnelConfig']();
}

export function OneClickStart() {
  return window['go']['main']['App']['OneClickStart']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function ReadClaudeCodeSettings() {
  return window['go']['main']['App']['ReadClaudeCodeSettings']();
}

export function ReadCredentialsRaw() {
  return window['go']['main']['App']['ReadCredentialsRaw']();
}

export function ReadDroidSettings() {
  return window['go']['main']['App']['ReadDroidSettings']();
}

export function ReadFactoryConfig() {
  return window['go']['main']['App']['ReadFactoryConfig']();
}

export function ReadOpenCodeConfig() {
  return window['go']['main']['App']['ReadOpenCodeConfig']();
}

export function RefreshNow() {
  return window['go']['main']['App']['RefreshNow']();
}

export function SaveAccountsToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveAccountsToFile'](arg1, arg2);
}

export function SaveConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4);
}

export function SaveCredentialsRaw(arg1) {
  return window['go']['main']['App']['SaveCredentialsRaw'](arg1);
}

export function SavePromptTemplate(arg1) {
  return window['go']['main']['App']['SavePromptTemplate'](arg1);
}

export function SaveServerSyncConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveServerSyncConfig'](arg1, arg2);
}

export function SaveTunnelConfig(arg1) {
  return window['go']['main']['App']['SaveTunnelConfig'](arg1);
}

export function SetExternalTunnel(arg1) {
  return window['go']['main']['App']['SetExternalTunnel'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StartTunnel() {
  return window['go']['main']['App']['StartTunnel']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function SyncAccount(arg1) {
  return window['go']['main']['App']['SyncAccount'](arg1);
}

export function TestServerConnection(arg1) {
  return window['go']['main']['App']['TestServerConnection'](arg1);
}

export function UpdateAccount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateAccountLabel(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccountLabel'](arg1, arg2);
}

export function UploadCredentialsToServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadCredentialsToServer'](arg1, arg2, arg3);
}

export function UseKeychainSource(arg1) {
  return window['go']['main']['App']['UseKeychainSource'](arg1);
}

export function WriteClaudeCodeSettings(arg1) {
  return window['go']['main']['App']['WriteClaudeCodeSettings'](arg1);
}

export function WriteDroidSettings(arg1) {
  return window['go']['main']['App']['WriteDroidSettings'](arg1);
}

export function WriteFactoryConfig(arg1) {
  return window['go']['main']['App']['WriteFactoryConfig'](arg1);
}

export function WriteOpenCodeConfig(arg1) {
  return window['go']['main']['App']['WriteOpenCodeConfig'](arg1);
}
